hello:
  pattern:    /
  controller: \PollMe\Controller\FooController::indexAction
  defaults:
      name:   you

register:
  pattern:    /register
  controller: \PollMe\Controller\RegistrationController::registerAction

submit_register:
  pattern:    /register
  controller: \PollMe\Controller\RegistrationController::submitRegisterAction
  method:     POST
