hello:
  pattern:    /
  controller: \PollMe\Controller\FooController::indexAction

login:
  pattern:    /login
  controller: \PollMe\Controller\LoginController::loginAction
  method:     POST

logout:
  pattern:    /logout
  controller: \PollMe\Controller\LoginController::logoutAction

register:
  pattern:    /register
  controller: \PollMe\Controller\RegistrationController::registerAction

submit_register:
  pattern:    /register
  controller: \PollMe\Controller\RegistrationController::submitRegisterAction
  method:     POST
