hello:
  pattern:    /hello
  controller: \PollMe\Controller\FooController::indexAction
  defaults:
      name:   you

hello_name:
  pattern:    /hello/:name
  controller: \PollMe\Controller\FooController::indexAction
