hello:
  pattern:    /hello
  controller: \PollMe\Controller\FooController::indexAction
  defaults:
      name:   you

hello_name:
  pattern:    /hello/:name
  controller: \PollMe\Controller\FooController::indexAction

register:
  pattern:    /register
  controller: \PollMe\Controller\RegistrationController::registerAction

submit_register:
  pattern:    /register
  controller: \PollMe\Controller\RegistrationController::submitRegisterAction
  method:     POST
