hello:
  pattern:    /
  controller: \PollMe\Controller\FooController::indexAction

login:
  pattern:    /login
  controller: \PollMe\Controller\LoginController::loginAction
  method:     POST

logout:
  pattern:    /logout
  controller: \PollMe\Controller\LoginController::logoutAction

register:
  pattern:    /register
  controller: \PollMe\Controller\RegistrationController::registerAction

submit_register:
  pattern:    /register
  controller: \PollMe\Controller\RegistrationController::submitRegisterAction
  method:     POST

surveys_new:
  pattern:    /surveys/new
  controller: \PollMe\Controller\SurveysController::newAction

surveys_create:
  pattern:    /surveys/new
  controller: \PollMe\Controller\SurveysController::createAction
  method:     POST

surveys_list_mine:
  pattern:    /surveys/mine
  controller: \PollMe\Controller\SurveysController::listMineAction

surveys_search:
  pattern:    /surveys/search
  controller: \PollMe\Controller\SurveysController::searchAction
  method:     POST

survey_vote:
  pattern:    /surveys/:survey_id/vote
  controller: \PollMe\Controller\SurveysController::voteAction
  method:     POST

change_password:
  pattern:    /account/password
  controller: \PollMe\Controller\UserAccountController::updatePasswordAction

submit_change_password:
  pattern:    /account/password
  controller: \PollMe\Controller\UserAccountController::doUpdatePasswordAction
  method:     POST
